update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 129 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 195 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 251 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 106 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 120 and "deletedAt" is NULL);
update contents set "maxScore" = 32 where 
   id IN (select "contentId" from qnas q where q.q_id = 8 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 264 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 179 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 209 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 276 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 110 and "deletedAt" is NULL);
update contents set "maxScore" = 40 where 
   id IN (select "contentId" from qnas q where q.q_id = 175 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 99 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 48 and "deletedAt" is NULL);
update contents set "maxScore" = 10 where 
   id IN (select "contentId" from qnas q where q.q_id = 28 and "deletedAt" is NULL);
update contents set "maxScore" = 120 where 
   id IN (select "contentId" from qnas q where q.q_id = 94 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 262 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 204 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 151 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 162 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 30 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 253 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 119 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 95 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 270 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 122 and "deletedAt" is NULL);
update contents set "maxScore" = 290 where 
   id IN (select "contentId" from qnas q where q.q_id = 62 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 268 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 214 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 180 and "deletedAt" is NULL);
update contents set "maxScore" = 180 where 
   id IN (select "contentId" from qnas q where q.q_id = 127 and "deletedAt" is NULL);
update contents set "maxScore" = 10 where 
   id IN (select "contentId" from qnas q where q.q_id = 101 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 20 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 25 and "deletedAt" is NULL);
update contents set "maxScore" = 120 where 
   id IN (select "contentId" from qnas q where q.q_id = 26 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 213 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 137 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 117 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 185 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 265 and "deletedAt" is NULL);
update contents set "maxScore" = 44 where 
   id IN (select "contentId" from qnas q where q.q_id = 168 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 136 and "deletedAt" is NULL);
update contents set "maxScore" = 180 where 
   id IN (select "contentId" from qnas q where q.q_id = 196 and "deletedAt" is NULL);
update contents set "maxScore" = 10 where 
   id IN (select "contentId" from qnas q where q.q_id = 218 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 238 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 27 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 230 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 155 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 149 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 93 and "deletedAt" is NULL);
update contents set "maxScore" = 212 where 
   id IN (select "contentId" from qnas q where q.q_id = 97 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 205 and "deletedAt" is NULL);
update contents set "maxScore" = 800 where 
   id IN (select "contentId" from qnas q where q.q_id = 197 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 187 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 114 and "deletedAt" is NULL);
update contents set "maxScore" = 180 where 
   id IN (select "contentId" from qnas q where q.q_id = 191 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 156 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 11 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 249 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 269 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 126 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 135 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 194 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 228 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 252 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 39 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 132 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 131 and "deletedAt" is NULL);
update contents set "maxScore" = 190 where 
   id IN (select "contentId" from qnas q where q.q_id = 67 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 178 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 255 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 241 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 17 and "deletedAt" is NULL);
update contents set "maxScore" = 120 where 
   id IN (select "contentId" from qnas q where q.q_id = 142 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 224 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 89 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 160 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 50 and "deletedAt" is NULL);
update contents set "maxScore" = 130 where 
   id IN (select "contentId" from qnas q where q.q_id = 57 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 109 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 51 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 239 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 31 and "deletedAt" is NULL);
update contents set "maxScore" = 190 where 
   id IN (select "contentId" from qnas q where q.q_id = 76 and "deletedAt" is NULL);
update contents set "maxScore" = 190 where 
   id IN (select "contentId" from qnas q where q.q_id = 69 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 203 and "deletedAt" is NULL);
update contents set "maxScore" = 186 where 
   id IN (select "contentId" from qnas q where q.q_id = 34 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 81 and "deletedAt" is NULL);
update contents set "maxScore" = 904 where 
   id IN (select "contentId" from qnas q where q.q_id = 219 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 12 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 273 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 10 and "deletedAt" is NULL);
update contents set "maxScore" = 160 where 
   id IN (select "contentId" from qnas q where q.q_id = 79 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 90 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 18 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 134 and "deletedAt" is NULL);
update contents set "maxScore" = 180 where 
   id IN (select "contentId" from qnas q where q.q_id = 59 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 139 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 146 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 143 and "deletedAt" is NULL);
update contents set "maxScore" = 140 where 
   id IN (select "contentId" from qnas q where q.q_id = 192 and "deletedAt" is NULL);
update contents set "maxScore" = 170 where 
   id IN (select "contentId" from qnas q where q.q_id = 98 and "deletedAt" is NULL);
update contents set "maxScore" = 180 where 
   id IN (select "contentId" from qnas q where q.q_id = 193 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 271 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 243 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 250 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 116 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 64 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 235 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 248 and "deletedAt" is NULL);
update contents set "maxScore" = 40 where 
   id IN (select "contentId" from qnas q where q.q_id = 84 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 145 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 207 and "deletedAt" is NULL);
update contents set "maxScore" = 904 where 
   id IN (select "contentId" from qnas q where q.q_id = 198 and "deletedAt" is NULL);
update contents set "maxScore" = 70 where 
   id IN (select "contentId" from qnas q where q.q_id = 74 and "deletedAt" is NULL);
update contents set "maxScore" = 4 where 
   id IN (select "contentId" from qnas q where q.q_id = 104 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 163 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 6 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 71 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 246 and "deletedAt" is NULL);
update contents set "maxScore" = 10 where 
   id IN (select "contentId" from qnas q where q.q_id = 29 and "deletedAt" is NULL);
update contents set "maxScore" = 140 where 
   id IN (select "contentId" from qnas q where q.q_id = 2 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 159 and "deletedAt" is NULL);
update contents set "maxScore" = 130 where 
   id IN (select "contentId" from qnas q where q.q_id = 72 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 267 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 186 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 234 and "deletedAt" is NULL);
update contents set "maxScore" = 40 where 
   id IN (select "contentId" from qnas q where q.q_id = 177 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 141 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 171 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 227 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 247 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 138 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 242 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 190 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 16 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 54 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 274 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 47 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 103 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 115 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 148 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 236 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 208 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 211 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 46 and "deletedAt" is NULL);
update contents set "maxScore" = 186 where 
   id IN (select "contentId" from qnas q where q.q_id = 36 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 15 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 174 and "deletedAt" is NULL);
update contents set "maxScore" = 300 where 
   id IN (select "contentId" from qnas q where q.q_id = 77 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 125 and "deletedAt" is NULL);
update contents set "maxScore" = 160 where 
   id IN (select "contentId" from qnas q where q.q_id = 140 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 4 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 153 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 200 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 257 and "deletedAt" is NULL);
update contents set "maxScore" = 120 where 
   id IN (select "contentId" from qnas q where q.q_id = 73 and "deletedAt" is NULL);
update contents set "maxScore" = 160 where 
   id IN (select "contentId" from qnas q where q.q_id = 56 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 182 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 53 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 222 and "deletedAt" is NULL);
update contents set "maxScore" = 834 where 
   id IN (select "contentId" from qnas q where q.q_id = 277 and "deletedAt" is NULL);
update contents set "maxScore" = 120 where 
   id IN (select "contentId" from qnas q where q.q_id = 123 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 261 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 275 and "deletedAt" is NULL);
update contents set "maxScore" = 94 where 
   id IN (select "contentId" from qnas q where q.q_id = 92 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 23 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 44 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 58 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 1 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 189 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 233 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 111 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 206 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 237 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 86 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 226 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 13 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 49 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 22 and "deletedAt" is NULL);
update contents set "maxScore" = 94 where 
   id IN (select "contentId" from qnas q where q.q_id = 91 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 70 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 45 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 225 and "deletedAt" is NULL);
update contents set "maxScore" = 10 where 
   id IN (select "contentId" from qnas q where q.q_id = 199 and "deletedAt" is NULL);
update contents set "maxScore" = 140 where 
   id IN (select "contentId" from qnas q where q.q_id = 60 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 165 and "deletedAt" is NULL);
update contents set "maxScore" = 20 where 
   id IN (select "contentId" from qnas q where q.q_id = 105 and "deletedAt" is NULL);
update contents set "maxScore" = 130 where 
   id IN (select "contentId" from qnas q where q.q_id = 21 and "deletedAt" is NULL);
update contents set "maxScore" = 70 where 
   id IN (select "contentId" from qnas q where q.q_id = 152 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 75 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 124 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 5 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 229 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 245 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 181 and "deletedAt" is NULL);
update contents set "maxScore" = 40 where 
   id IN (select "contentId" from qnas q where q.q_id = 220 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 259 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 166 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 112 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 254 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 3 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 201 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 61 and "deletedAt" is NULL);
update contents set "maxScore" = 40 where 
   id IN (select "contentId" from qnas q where q.q_id = 176 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 87 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 169 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 14 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 107 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 147 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 221 and "deletedAt" is NULL);
update contents set "maxScore" = 160 where 
   id IN (select "contentId" from qnas q where q.q_id = 121 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 210 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 258 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 161 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 19 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 108 and "deletedAt" is NULL);
update contents set "maxScore" = 90 where 
   id IN (select "contentId" from qnas q where q.q_id = 157 and "deletedAt" is NULL);
update contents set "maxScore" = 70 where 
   id IN (select "contentId" from qnas q where q.q_id = 154 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 215 and "deletedAt" is NULL);
update contents set "maxScore" = 180 where 
   id IN (select "contentId" from qnas q where q.q_id = 35 and "deletedAt" is NULL);
update contents set "maxScore" = 130 where 
   id IN (select "contentId" from qnas q where q.q_id = 65 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 52 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 85 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 173 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 32 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 188 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 164 and "deletedAt" is NULL);
update contents set "maxScore" = 300 where 
   id IN (select "contentId" from qnas q where q.q_id = 78 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 133 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 150 and "deletedAt" is NULL);
update contents set "maxScore" = 100 where 
   id IN (select "contentId" from qnas q where q.q_id = 100 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 232 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 158 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 113 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 172 and "deletedAt" is NULL);
update contents set "maxScore" = 40 where 
   id IN (select "contentId" from qnas q where q.q_id = 63 and "deletedAt" is NULL);
update contents set "maxScore" = 192 where 
   id IN (select "contentId" from qnas q where q.q_id = 9 and "deletedAt" is NULL);
update contents set "maxScore" = 50 where 
   id IN (select "contentId" from qnas q where q.q_id = 183 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 24 and "deletedAt" is NULL);
update contents set "maxScore" = 70 where 
   id IN (select "contentId" from qnas q where q.q_id = 184 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 260 and "deletedAt" is NULL);
update contents set "maxScore" = 200 where 
   id IN (select "contentId" from qnas q where q.q_id = 170 and "deletedAt" is NULL);
update contents set "maxScore" = 150 where 
   id IN (select "contentId" from qnas q where q.q_id = 55 and "deletedAt" is NULL);
update contents set "maxScore" = 70 where 
   id IN (select "contentId" from qnas q where q.q_id = 88 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 118 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 244 and "deletedAt" is NULL);
update contents set "maxScore" = 120 where 
   id IN (select "contentId" from qnas q where q.q_id = 130 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 272 and "deletedAt" is NULL);
update contents set "maxScore" = 120 where 
   id IN (select "contentId" from qnas q where q.q_id = 38 and "deletedAt" is NULL);
update contents set "maxScore" = 60 where 
   id IN (select "contentId" from qnas q where q.q_id = 128 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 223 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 240 and "deletedAt" is NULL);
update contents set "maxScore" = 894 where 
   id IN (select "contentId" from qnas q where q.q_id = 217 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 231 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 212 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 256 and "deletedAt" is NULL);
update contents set "maxScore" = 964 where 
   id IN (select "contentId" from qnas q where q.q_id = 216 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 263 and "deletedAt" is NULL);
update contents set "maxScore" = 110 where 
   id IN (select "contentId" from qnas q where q.q_id = 202 and "deletedAt" is NULL);
update contents set "maxScore" = 30 where 
   id IN (select "contentId" from qnas q where q.q_id = 266 and "deletedAt" is NULL);
update contents set "maxScore" = 80 where 
   id IN (select "contentId" from qnas q where q.q_id = 144 and "deletedAt" is NULL);
update contents set "maxScore" = 74 where 
   id IN (select "contentId" from qnas q where q.q_id = 7 and "deletedAt" is NULL);
